package com.example.seleniumtemplate.reporting;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import com.example.seleniumtemplate.api.support.LocalApiFixture;
import com.example.seleniumtemplate.core.api.ApiClient;
import com.example.seleniumtemplate.core.api.ApiExchangeFilter;
import com.example.seleniumtemplate.core.api.ApiRequestFactory;
import com.example.seleniumtemplate.core.config.ApiConfig;
import com.example.seleniumtemplate.core.config.DatabaseConfig;
import com.example.seleniumtemplate.core.db.DatabaseClient;
import com.example.seleniumtemplate.core.db.DatabaseManager;
import com.example.seleniumtemplate.core.db.DatabaseDiagnostics;
import com.example.seleniumtemplate.support.reporting.FailureDiagnostics;
import java.time.Duration;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import org.jspecify.annotations.Nullable;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class ReportingDiagnosticsReliabilityTest {

    private @Nullable LocalApiFixture apiFixture;
    private @Nullable ApiClient api;
    private @Nullable DatabaseManager databaseManager;
    private @Nullable DatabaseClient db;

    @BeforeClass
    public void startFixtures() {
        LocalApiFixture startedApi = LocalApiFixture.start();
        apiFixture = startedApi;
        api = new ApiClient(new ApiRequestFactory(new ApiConfig(
                startedApi.baseUri(),
                Duration.ofSeconds(3),
                Duration.ofSeconds(5))));

        DatabaseManager startedDb = new DatabaseManager(new DatabaseConfig(
                "jdbc:h2:mem:reporting_diagnostics;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
                "sa",
                "",
                4,
                Duration.ofSeconds(5)));
        databaseManager = startedDb;
        db = startedDb.client();
        db.update("""
                CREATE TABLE IF NOT EXISTS probe (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(64) NOT NULL
                )
                """);
    }

    @AfterClass(alwaysRun = true)
    public void stopFixtures() {
        LocalApiFixture startedApi = apiFixture;
        if (startedApi != null) {
            startedApi.close();
        }
        DatabaseManager startedDb = databaseManager;
        if (startedDb != null) {
            startedDb.close();
        }
    }

    @BeforeMethod
    public void clearDiagnostics() {
        FailureDiagnostics.clearThreadState();
    }

    @Test
    public void sensitiveApiHeadersAreMaskedInCapturedExchange() {
        ApiClient authorized = new ApiClient(
                new ApiRequestFactory(new ApiConfig(
                        Objects.requireNonNull(apiFixture, "apiFixture").baseUri(),
                        Duration.ofSeconds(3),
                        Duration.ofSeconds(5))),
                request -> request.header("Authorization", "Bearer secret-token")
                        .header("X-API-Key", "secret-key")
                        .header("Cookie", "session=secret"));

        authorized.get("/whoami");

        ApiExchangeFilter.Exchange exchange = Objects.requireNonNull(
                ApiExchangeFilter.lastExchange(),
                "expected API exchange");
        assertThat(exchange.requestHeaders().get("Authorization")).isEqualTo("***");
        assertThat(exchange.requestHeaders().get("X-API-Key")).isEqualTo("***");
        assertThat(exchange.requestHeaders().get("Cookie")).isEqualTo("***");
        assertThat(exchange.requestHeaders().values())
                .doesNotContain("Bearer secret-token", "secret-key", "session=secret");
        assertThat(exchange.render())
                .contains("Authorization=***")
                .contains("X-API-Key=***")
                .contains("Cookie=***");
    }

    @Test
    public void diagnosticThreadLocalsAreCleared() {
        api().get("/health");
        assertThat(ApiExchangeFilter.lastExchange()).isNotNull();

        try {
            db().update("INSERT INTO missing_table(name) VALUES (?)", "x");
        } catch (RuntimeException ignored) {
            // expected: populates DatabaseDiagnostics
        }
        assertThat(DatabaseDiagnostics.lastFailure()).isNotNull();

        FailureDiagnostics.clearThreadState();

        assertThat(ApiExchangeFilter.lastExchange()).isNull();
        assertThat(DatabaseDiagnostics.lastFailure()).isNull();
    }

    @Test
    public void apiExchangeCaptureIsIsolatedBetweenParallelThreads() throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        CountDownLatch ready = new CountDownLatch(2);
        CountDownLatch start = new CountDownLatch(1);
        ConcurrentHashMap<String, String> captured = new ConcurrentHashMap<>();

        try {
            executor.execute(() -> captureEcho(ready, start, captured, "alpha"));
            executor.execute(() -> captureEcho(ready, start, captured, "beta"));

            assertThat(ready.await(5, TimeUnit.SECONDS)).isTrue();
            start.countDown();
            executor.shutdown();
            assertThat(executor.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
        } finally {
            executor.shutdownNow();
        }

        assertThat(captured)
                .containsEntry("alpha", "alpha")
                .containsEntry("beta", "beta");
    }

    @Test
    public void dbDiagnosticContextIsIsolatedBetweenParallelThreads() throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        CountDownLatch ready = new CountDownLatch(2);
        CountDownLatch start = new CountDownLatch(1);
        ConcurrentHashMap<String, String> captured = new ConcurrentHashMap<>();

        try {
            executor.execute(() -> captureDbFailure(ready, start, captured, "one"));
            executor.execute(() -> captureDbFailure(ready, start, captured, "two"));

            assertThat(ready.await(5, TimeUnit.SECONDS)).isTrue();
            start.countDown();
            executor.shutdown();
            assertThat(executor.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
        } finally {
            executor.shutdownNow();
        }

        assertThat(captured.get("one")).contains("one");
        assertThat(captured.get("two")).contains("two");
        assertThat(captured.get("one")).doesNotContain("two");
        assertThat(captured.get("two")).doesNotContain("one");
    }

    @Test
    public void attachAvailableDoesNotThrowWhenBrowserUnavailable() {
        assertThat(com.example.seleniumtemplate.core.ApplicationContext.currentOrNull()).isNull();

        assertThatCode(FailureDiagnostics::attachAvailable).doesNotThrowAnyException();
    }

    private void captureEcho(
            CountDownLatch ready,
            CountDownLatch start,
            ConcurrentHashMap<String, String> captured,
            String name) {
        try {
            ready.countDown();
            start.await(5, TimeUnit.SECONDS);
            api().get("/echo-query", java.util.Map.of("name", name));
            ApiExchangeFilter.Exchange exchange = Objects.requireNonNull(
                    ApiExchangeFilter.lastExchange(),
                    "exchange");
            captured.put(name, Objects.requireNonNull(
                    exchange.uri().contains("name=" + name) ? name : exchange.uri(),
                    "captured"));
        } catch (Exception ex) {
            throw new IllegalStateException("parallel API capture failed for " + name, ex);
        } finally {
            ApiExchangeFilter.clear();
        }
    }

    private void captureDbFailure(
            CountDownLatch ready,
            CountDownLatch start,
            ConcurrentHashMap<String, String> captured,
            String marker) {
        try {
            ready.countDown();
            start.await(5, TimeUnit.SECONDS);
            try {
                db().update("INSERT INTO missing_" + marker + "(name) VALUES (?)", marker);
            } catch (RuntimeException ignored) {
                // expected
            }
            DatabaseDiagnostics.Failure failure = Objects.requireNonNull(
                    DatabaseDiagnostics.lastFailure(),
                    "db failure");
            captured.put(marker, failure.sql());
        } catch (Exception ex) {
            throw new IllegalStateException("parallel DB capture failed for " + marker, ex);
        } finally {
            DatabaseDiagnostics.clear();
        }
    }

    private ApiClient api() {
        return Objects.requireNonNull(api, "api");
    }

    private DatabaseClient db() {
        return Objects.requireNonNull(db, "db");
    }
}
