package com.example.seleniumtemplate.db.support;

import com.example.seleniumtemplate.core.db.DatabaseClient;
import java.util.Objects;

public final class LocalDbSchema {

    private LocalDbSchema() {
    }

    public static void create(DatabaseClient db) {
        Objects.requireNonNull(db, "db must not be null");
        db.update("""
                CREATE TABLE IF NOT EXISTS users (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  email VARCHAR(255) NOT NULL UNIQUE,
                  name VARCHAR(255) NOT NULL,
                  active BOOLEAN NOT NULL DEFAULT TRUE
                )
                """);
        db.update("""
                CREATE TABLE IF NOT EXISTS orders (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  user_id BIGINT NOT NULL,
                  amount DECIMAL(19, 2) NOT NULL
                )
                """);
    }
}
