package com.example.seleniumtemplate.db;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.example.seleniumtemplate.core.config.DatabaseConfig;
import com.example.seleniumtemplate.core.db.DatabaseClient;
import com.example.seleniumtemplate.core.db.DatabaseManager;
import com.example.seleniumtemplate.db.support.LocalDbSchema;
import com.example.seleniumtemplate.db.support.UserFixtures;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.jspecify.annotations.Nullable;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class DatabaseClientReliabilityTest {

    private @Nullable DatabaseManager manager;
    private @Nullable DatabaseClient db;
    private @Nullable UserFixtures users;

    @BeforeClass
    public void startDatabase() {
        DatabaseManager started = new DatabaseManager(new DatabaseConfig(
                "jdbc:h2:mem:db_client_reliability;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
                "sa",
                "",
                8,
                Duration.ofSeconds(5)));
        manager = started;
        DatabaseClient client = started.client();
        db = client;
        LocalDbSchema.create(client);
        users = new UserFixtures(client);
    }

    @AfterClass(alwaysRun = true)
    public void stopDatabase() {
        DatabaseManager started = manager;
        if (started != null) {
            started.close();
        }
    }

    @BeforeMethod
    public void cleanTables() {
        db().update("DELETE FROM orders");
        db().update("DELETE FROM users");
    }

    @Test
    public void updateInsertsRow() {
        int updated = db().update(
                "INSERT INTO users(email, name, active) VALUES (?, ?, ?)",
                "insert@example.test",
                "Insert",
                true);

        assertThat(updated).isEqualTo(1);
        assertThat(db().queryScalar("SELECT COUNT(*) FROM users", Long.class)).isEqualTo(1L);
    }

    @Test
    public void queryReturnsRows() {
        users().createUser("a@example.test", "A");
        users().createUser("b@example.test", "B");

        List<Map<String, Object>> rows = db().query(
                "SELECT email FROM users WHERE email LIKE ? ORDER BY email",
                "%@example.test");

        assertThat(rows).hasSize(2);
        assertThat(rows.get(0)).containsEntry("email", "a@example.test");
        assertThat(rows.get(1)).containsEntry("email", "b@example.test");
    }

    @Test
    public void queryOneRequiresExactlyOneRow() {
        users().createUser("one@example.test", "One");

        Map<String, Object> row = db().queryOne(
                "SELECT email, name FROM users WHERE email = ?",
                "one@example.test");
        assertThat(row).containsEntry("email", "one@example.test").containsEntry("name", "One");

        assertThatThrownBy(() -> db().queryOne(
                        "SELECT email FROM users WHERE email = ?",
                        "missing@example.test"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("found 0");

        users().createUser("two@example.test", "Two");
        assertThatThrownBy(() -> db().queryOne("SELECT email FROM users"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("found 2");
    }

    @Test
    public void queryPreservesSqlNullAsJavaNullInUnmodifiableRow() {
        db().update("""
                CREATE TABLE IF NOT EXISTS null_probe (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  label VARCHAR(255)
                )
                """);
        db().update("DELETE FROM null_probe");
        db().update("INSERT INTO null_probe(label) VALUES (?)", new Object[] {null});

        List<Map<String, Object>> rows = db().query("SELECT id, label FROM null_probe");
        assertThat(rows).hasSize(1);
        assertThat(rows.getFirst().get("label")).isNull();

        Map<String, Object> row = db().queryOne("SELECT id, label FROM null_probe");
        assertThat(row.get("label")).isNull();
        assertThat(row).containsKey("label");

        assertThatThrownBy(() -> row.put("label", "mutated"))
                .isInstanceOf(UnsupportedOperationException.class);
    }

    @Test
    public void queryOptionalEmptyAndOne() {
        Optional<Map<String, Object>> missing = db().queryOptional(
                "SELECT email FROM users WHERE email = ?",
                "missing@example.test");
        assertThat(missing).isEmpty();

        users().createUser("opt@example.test", "Optional");
        Optional<Map<String, Object>> present = db().queryOptional(
                "SELECT email FROM users WHERE email = ?",
                "opt@example.test");
        assertThat(present).isPresent();
        assertThat(present.orElseThrow()).containsEntry("email", "opt@example.test");

        users().createUser("opt2@example.test", "Optional2");
        assertThatThrownBy(() -> db().queryOptional("SELECT email FROM users"))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("found 2");
    }

    @Test
    public void queryScalarReturnsTypedValue() {
        users().createUser("scalar@example.test", "Scalar");

        Long count = db().queryScalar("SELECT COUNT(*) FROM users", Long.class);
        String email = db().queryScalar(
                "SELECT email FROM users WHERE email = ?",
                String.class,
                "scalar@example.test");

        assertThat(count).isEqualTo(1L);
        assertThat(email).isEqualTo("scalar@example.test");
    }

    @Test
    public void parameterBindingPreventsLiteralConcatenationNeed() {
        users().createUser("bind@example.test", "Bind");

        Map<String, Object> row = db().queryOne(
                "SELECT name FROM users WHERE email = ?",
                "bind@example.test");

        assertThat(row).containsEntry("name", "Bind");
        assertThat(db().query(
                        "SELECT email FROM users WHERE email = ?",
                        "bind@example.test' OR '1'='1"))
                .isEmpty();
    }

    @Test
    public void insertAndReturnGeneratedKeyReturnsIdentity() {
        long id = users().createUser("key@example.test", "Key");

        assertThat(id).isPositive();
        Map<String, Object> row = db().queryOne("SELECT id, email FROM users WHERE id = ?", id);
        assertThat(((Number) Objects.requireNonNull(row.get("id"))).longValue()).isEqualTo(id);
        assertThat(row).containsEntry("email", "key@example.test");
    }

    @Test
    public void transactionCommitsDependentStatements() {
        long userId = db().inTransaction(tx -> {
            long id = tx.insertAndReturnGeneratedKey(
                    "INSERT INTO users(email, name, active) VALUES (?, ?, ?)",
                    "tx@example.test",
                    "Tx",
                    true);
            tx.update(
                    "INSERT INTO orders(user_id, amount) VALUES (?, ?)",
                    id,
                    java.math.BigDecimal.valueOf(42.50));
            return id;
        });

        assertThat(db().queryScalar(
                        "SELECT COUNT(*) FROM orders WHERE user_id = ?",
                        Long.class,
                        userId))
                .isEqualTo(1L);
    }

    @Test
    public void transactionRollsBackOnException() {
        assertThatThrownBy(() -> db().inTransaction(tx -> {
                    tx.update(
                            "INSERT INTO users(email, name, active) VALUES (?, ?, ?)",
                            "rollback@example.test",
                            "Rollback",
                            true);
                    throw new IllegalStateException("boom");
                }))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("boom");

        assertThat(db().queryScalar(
                        "SELECT COUNT(*) FROM users WHERE email = ?",
                        Long.class,
                        "rollback@example.test"))
                .isEqualTo(0L);
    }

    @Test
    public void batchInsertsMultipleRows() {
        int[] counts = db().batch(
                "INSERT INTO users(email, name, active) VALUES (?, ?, ?)",
                List.of(
                        new Object[] {"batch1@example.test", "B1", true},
                        new Object[] {"batch2@example.test", "B2", false},
                        new Object[] {"batch3@example.test", "B3", true}));

        assertThat(counts).containsExactly(1, 1, 1);
        assertThat(db().queryScalar("SELECT COUNT(*) FROM users", Long.class)).isEqualTo(3L);
    }

    @Test
    public void parallelOperationsDoNotShareConnectionState() throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(4);
        CountDownLatch ready = new CountDownLatch(4);
        CountDownLatch start = new CountDownLatch(1);
        ConcurrentHashMap<String, Long> results = new ConcurrentHashMap<>();
        AtomicInteger failures = new AtomicInteger();

        try {
            for (int i = 1; i <= 4; i++) {
                String email = "parallel-" + i + "@example.test";
                executor.execute(() -> {
                    try {
                        ready.countDown();
                        start.await(5, TimeUnit.SECONDS);
                        long id = users().createUser(email, email);
                        Long found = db().queryScalar(
                                "SELECT id FROM users WHERE email = ?",
                                Long.class,
                                email);
                        results.put(email, found);
                        assertThat(found).isEqualTo(id);
                    } catch (Exception ex) {
                        failures.incrementAndGet();
                        throw new IllegalStateException("parallel DB operation failed for " + email, ex);
                    }
                });
            }

            assertThat(ready.await(5, TimeUnit.SECONDS)).isTrue();
            start.countDown();
            executor.shutdown();
            assertThat(executor.awaitTermination(15, TimeUnit.SECONDS)).isTrue();
        } finally {
            executor.shutdownNow();
        }

        assertThat(failures.get()).isZero();
        assertThat(results).hasSize(4);
        assertThat(db().queryScalar("SELECT COUNT(*) FROM users", Long.class)).isEqualTo(4L);
    }

    private DatabaseClient db() {
        return Objects.requireNonNull(db, "db");
    }

    private UserFixtures users() {
        return Objects.requireNonNull(users, "users");
    }
}
